### ISSUE TITLE
Running mpw-js on NodeMCU microcontroller

### ISSUE THREAD

**Issue by wuhanstudio** [tmthrgd/mpw-js#10]
Exceuse me, can I use your mpw-js code in my project?

I've managed to serve mpw-js on a 32bit microcontroller. To make this happen, I have to fit the source code into 50K so that I've compressed the javascript file which makes it not human readable. I'm sorry this destroyed your comments relating to license.

So I've added your project link to the readme file on the bottom. Is it OK ?

Thank you very much.

Project link :

> https://github.com/wuhanstudio/masterpassword-nodemcu

**Comment by tmthrgd** [comment]
@wuhanstudio That seems suitable to me. I'm glad mpw-js fits your needs, best of luck to your project. 👍
