### ISSUE TITLE
Wrong passwords when name contains non-ascii characters

### ISSUE THREAD

**Issue by ujaroe** [tmthrgd/mpw-js#3]
When the user name contains umlauts (for example) the generated password is apparently wrong.

Example:
Full name: Jens Weißmüller
Master Password: 123
Site: eBay
Counter: 1
Template: Medium

Generated: Yar8/Fos
Correct: JidHeh8_

**Comment by tmthrgd** [comment]
I've closed this issue as 'Desktop (Java)' now also reflects the correct behaviour.
