### ISSUE TITLE
Compile scrypt from source

### ISSUE THREAD

**Issue by tmthrgd** [tmthrgd/mpw-js#4]
@lhunath and @cuardin (and others?) behind/working-with Master Password have asked for `scrypt-asm.js` to be able to be emscripten compiled from it's c source code. Thus no longer relying on [tonyg/js-scrypt](https://github.com/tonyg/js-scrypt).

As this is viewed as a stumbling block for long-term stable use of [tmthrgd/mpw-js](https://github.com/tmthrgd/mpw-js), it will be considered a priority.

The non-Github issue trackers for this are [MP-14](https://project.lyndir.com/youtrack/issue/MP-14), [MP-1](https://project.lyndir.com/youtrack/issue/MP-1) and [MP-17](https://project.lyndir.com/youtrack/issue/MP-17).

**Comment by tmthrgd** [comment]
I have managed to successfully compile scrypt using [the Makefile](https://github.com/tonyg/js-scrypt/blob/master/Makefile). Emscripten can be installed by following the instructions at [Download and install - Emscripten 1.29.1 documentation](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html).

**Comment by tmthrgd** [comment]
I'm closing this issue as I believe it has been sufficiently resolved.

**Comment by tmthrgd** [comment]
With 3890373670d997be6b89fe1bd13ee1759a68810d this is now open again.

**Comment by ttyridal** [comment]
Hi, you could have a look at the scrypt I emscript compiled here https://github.com/ttyridal/masterpassword-firefox/tree/master/libscrypt
It seems to work without problems, and is actually performing quite a lot better than your/tonyg's version on the browser's I've tested.

**Comment by tmthrgd** [comment]
This has now been resolved with a50e966. `scrypt-asm.js` has been replaced with a pure javascript version.

**Comment by tmthrgd** [comment]
This has now been resolved with a50e966. `scrypt-asm.js` has been replaced with a pure javascript version.
