### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by lhunath** [tmthrgd/mpw-js#6]
Would it be possible to provide tests that run the implementation through https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-algorithm/src/test/resources/mpw_tests.xml and check whether it yields correct results for each test case?  Ideally, these tests would be runnable from the command-line, eg. using node.

I've taken js.masterpasswordapp.com down since it seemed to be generating bad passwords, until I figure out why.  I want to avoid this in the future.

**Comment by tmthrgd** [comment]
I have implemented a working test suited and am working to fix bugs before uploading it.

All `v0_` tests currently fail; this is being considered **wontfix**.
All `_mb_` tests currently fail; this is considered a **bug**.

@lhunath Are the [mpw_tests.xml](https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-algorithm/src/test/resources/mpw_tests.xml) consistent with #3 or not?

**Comment by lhunath** [comment]
Note I just updated the file and the C and Java tests now pass.  They didn't before.

**Comment by lhunath** [comment]
WRT. #3, that should be fixed in `v3_`.

**Comment by tmthrgd** [comment]
The test suite can be found at <https://tmthrgd.github.io/mpw-js/test/>.

**Comment by tmthrgd** [comment]
Excluding `v0_`, all but three errors have been resolved. `mpw-js` now passes the `v3_` test with flying colours. The other issues *may* be fixed but as they are related to old versions fixes may not be forthcoming.

**Comment by tmthrgd** [comment]
This issue has now been resolved.

**Comment by tmthrgd** [comment]
`mpw-js` now passes **all** `v1_`, `v2_` and `v3_` tests.

**Comment by tmthrgd** [comment]
`mpw-js` now supports `v0_` and passes all `v0_` tests.

**Comment by lhunath** [comment]
Nice!
