### ISSUE TITLE
JavaScript error, form doesn't work

### ISSUE THREAD

**Issue by tbreuss** [tmthrgd/mpw-js#9]
I'm getting a JS error while trying your demo application at: https://tmthrgd.github.io/mpw-js/

Tested on Chrome Version 57.0.2987.98 (64-bit) and Safari Version 10.0.3 (12602.4.8).

![js-error](https://cloud.githubusercontent.com/assets/1334161/24329616/500adc8a-120c-11e7-9012-8b98b50f33d2.png)

**Comment by tmthrgd** [comment]
Thank you for the bug report. This was known behaviour and didn't effect the functionality at all, but the error is quite easily avoided, so it should be avoided.
